### ISSUE TITLE
Fails to compile on macOS 10.11.6

### ISSUE THREAD

**Issue by jirutka** [spacewander/luabenchmark#2]
```
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/usr/local/include -c benchmarklib.c -o benchmarklib.o
benchmarklib.c:56:9: error: expected identifier or '('
    int CLK_TCK = sysconf(_SC_CLK_TCK);
        ^
/usr/include/i386/limits.h:46:18: note: expanded from macro 'CLK_TCK'
#define CLK_TCK         __DARWIN_CLK_TCK        /* ticks per second */
                        ^
/usr/include/i386/_limits.h:25:27: note: expanded from macro '__DARWIN_CLK_TCK'
#define __DARWIN_CLK_TCK                100     /* ticks per second */
                                        ^
benchmarklib.c:66:5: warning: implicit declaration of function 'clock_gettime' is invalid in C99 [-Wimplicit-function-declaration]
    clock_gettime(CLOCK_MONOTONIC, &ts);
    ^
benchmarklib.c:66:19: error: use of undeclared identifier 'CLOCK_MONOTONIC'
    clock_gettime(CLOCK_MONOTONIC, &ts);
                  ^
1 warning and 2 errors generated.

Error: Build error: Failed compiling object benchmarklib.o
```
